version: "3.7"
services:
  ddclient:
    image: znibb/ddclient:latest
    container_name: ddclient
    init: true
    labels:
     - "com.centurylinklabs.watchtower.enable=true"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    network_mode: bridge
    restart: unless-stopped
    volumes:
     - /etc/timezone:/etc/timezone:ro
     - ./ddclient.conf:/ddclient/ddclient.conf
