version: "3.7"
services:
  ddclient:
    image: znibb/ddclient:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
     - "/etc/timezone:/etc/timezone:ro"
     - "/etc/localtime:/etc/localtime:ro"
    configs:
     - source: ddclient_config_v1
       target: /etc/ddclient.conf
       uid: '0'
       gid: '0'
       mode: 0600
    secrets:
     - source: ddclient_passwd
       target: ddclient_passwd
       uid: '0'
       gid: '0'
       mode: 0400
    networks:
     - ddclient

configs:
  ddclient_config_v1:
    external: true

secrets:
  ddclient_passwd:
    external: true

networks:
  ddclient:
