services:
  ddclient:
    image: linuxserver/ddclient:latest
    container_name: ddclient
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - .env
    environment:
      - PUID=${PUID:?}
      - PGID=${PGID:?}
      - TZ=${TZ:-Etc/UTC}
    labels:
     - "com.centurylinklabs.watchtower.enable=true"
    network_mode: bridge
    restart: unless-stopped
    volumes:
     - ./ddclient.conf:/config/ddclient.conf
